on:
  push:
    branches:
      - master


  build_deploy_production:
    if: (github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master')
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.5.7 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }} # your  heroku api key
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }} # you aplication name
          heroku_email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
          usedocker: true
